# Testing with conda - heavier than the PIP version,
# this includes different engines and plugins

name: Tests with Conda

on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
  schedule:
    - cron: '36 21 * * 6'

jobs:
  build-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          # - macOS-latest
          - ubuntu-latest
        python-version:
          - "3.8"
          - "3.9"
    env:
      CI_OS: ${{ matrix.os }}
      PYVER: ${{ matrix.python-version }}
      PACKAGE: geometric

    steps:
      - uses: actions/checkout@v3

      - name: Set up conda environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: devtools/conda-envs/latest.yaml
          create-args: >- # beware the >- instead of |, we don't split on newlines but on spaces
            python=${{ matrix.python-version }}

      # Old version commented out 2023-10-25
      # - name: Add conda to system path
      #   run: |
      #     # $CONDA is an environment variable pointing to the root of the miniconda directory
      #     echo $CONDA/bin >> $GITHUB_PATH
      # 
      # # - name: Configure Conda
      # #   run: conda config --set channel_priority flexible
      # - name: Install Mamba
      #   run: conda install -c conda-forge mamba
      # 
      # - name: Install Dependencies
      #   run: mamba env update --file=devtools/conda-envs/latest.yaml --name=base
      # 
      - name: Activate environment
        run: |
          micromamba activate geometric-test

      - name: Environment Information
        run: |
          conda info --all
          conda list

      - name: Install package
        run: |
          python -c "import numpy; print(numpy.__version__)"
          python -m pip install --no-deps .
          python -c "import numpy; print(numpy.__version__)"
          python -c "import geometric; print(geometric.__version__)"

      - name: pytest
        run: pytest -v --cov=geometric  geometric/tests/

      # LPW 2022-10-03 Commenting out because GH Actions cannot test or cover Engine interfaces to commercial packages.
      # Enabling Codecov upload for GH Actions would undercount the lines actually covered.
      # - name: Codecov upload
      #   uses: codecov/codecov-action@v1
      #   with:
      #     flags: unittests-conda
      #     fail_ci_if_error: true
      #     verbose: true
